
package View;

import Controller.ProjetoController;
import Model.Tabelas.Projeto;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

public class AdmAcompanharProjetos extends javax.swing.JFrame {

    ProjetoController projController;
    
    /**
     * Creates new form ProjetosAdministrador
     */
    public AdmAcompanharProjetos() {
        initComponents();
        projController = new ProjetoController();
        tabelaProjetosAdmin = projController.updateTable(tabelaProjetosAdmin, "Aprovado");
        
        // Esconde a coluna com os IDs.
        tabelaProjetosAdmin.removeColumn(tabelaProjetosAdmin.getColumnModel().getColumn(0));
        
        // Para utilização mais tarde
        //System.out.println("Id: " + tabelaProjetosAdmin.getModel().getValueAt(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projetosAdminContentPanel = new javax.swing.JPanel();
        projetosAdminIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProjetosAdmin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        altStatusProjeto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox();
        tituloTextField = new javax.swing.JTextField();
        areaTextField = new javax.swing.JTextField();
        profOrientadorTextField = new javax.swing.JTextField();
        alunoLiderTextField = new javax.swing.JTextField();
        projetosAdminMenuPanel = new javax.swing.JPanel();
        indexMenuPanel = new javax.swing.JPanel();
        bttnVoltarProjetosAdmin = new javax.swing.JButton();
        bttnAltStatusProjeto = new javax.swing.JButton();
        altStatusMenuPanel = new javax.swing.JPanel();
        bttnVoltarProjetos = new javax.swing.JButton();
        bttnConfirmarAlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projetosAdminContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projetosAdminContentPanel.setLayout(new java.awt.CardLayout());

        tabelaProjetosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Líder", "Orientador", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProjetosAdmin);
        if (tabelaProjetosAdmin.getColumnModel().getColumnCount() > 0) {
            tabelaProjetosAdmin.getColumnModel().getColumn(0).setResizable(false);
            tabelaProjetosAdmin.getColumnModel().getColumn(1).setResizable(false);
            tabelaProjetosAdmin.getColumnModel().getColumn(2).setResizable(false);
            tabelaProjetosAdmin.getColumnModel().getColumn(3).setResizable(false);
            tabelaProjetosAdmin.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Projetos Aprovados");

        javax.swing.GroupLayout projetosAdminIndexLayout = new javax.swing.GroupLayout(projetosAdminIndex);
        projetosAdminIndex.setLayout(projetosAdminIndexLayout);
        projetosAdminIndexLayout.setHorizontalGroup(
            projetosAdminIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetosAdminIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(projetosAdminIndexLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projetosAdminIndexLayout.setVerticalGroup(
            projetosAdminIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projetosAdminIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        projetosAdminContentPanel.add(projetosAdminIndex, "projetosAdminIndex");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Alterar Status do Projeto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Área:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Professor Orientador:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Aluno Líder:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("NOVO STATUS:");

        statusComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Em execução", "Encerrado", "Inativo" }));

        tituloTextField.setEditable(false);

        areaTextField.setEditable(false);

        profOrientadorTextField.setEditable(false);

        alunoLiderTextField.setEditable(false);

        javax.swing.GroupLayout altStatusProjetoLayout = new javax.swing.GroupLayout(altStatusProjeto);
        altStatusProjeto.setLayout(altStatusProjetoLayout);
        altStatusProjetoLayout.setHorizontalGroup(
            altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altStatusProjetoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(192, 192, 192))
                    .addGroup(altStatusProjetoLayout.createSequentialGroup()
                        .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alunoLiderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(profOrientadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(174, Short.MAX_VALUE))))
        );
        altStatusProjetoLayout.setVerticalGroup(
            altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altStatusProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altStatusProjetoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profOrientadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alunoLiderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(altStatusProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        projetosAdminContentPanel.add(altStatusProjeto, "altStatusProjeto");

        projetosAdminMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projetosAdminMenuPanel.setLayout(new java.awt.CardLayout());

        bttnVoltarProjetosAdmin.setText("Voltar");
        bttnVoltarProjetosAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarProjetosAdminActionPerformed(evt);
            }
        });

        bttnAltStatusProjeto.setText("Alterar Status do Projeto");
        bttnAltStatusProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAltStatusProjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indexMenuPanelLayout = new javax.swing.GroupLayout(indexMenuPanel);
        indexMenuPanel.setLayout(indexMenuPanelLayout);
        indexMenuPanelLayout.setHorizontalGroup(
            indexMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(indexMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(indexMenuPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(bttnAltStatusProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(370, 370, 370)
                    .addComponent(bttnVoltarProjetosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        indexMenuPanelLayout.setVerticalGroup(
            indexMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
            .addGroup(indexMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(indexMenuPanelLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(indexMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bttnAltStatusProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnVoltarProjetosAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        projetosAdminMenuPanel.add(indexMenuPanel, "indexMenuPanel");

        bttnVoltarProjetos.setText("Voltar");
        bttnVoltarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarProjetosActionPerformed(evt);
            }
        });

        bttnConfirmarAlt.setText("Confirmar alteração");
        bttnConfirmarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmarAltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout altStatusMenuPanelLayout = new javax.swing.GroupLayout(altStatusMenuPanel);
        altStatusMenuPanel.setLayout(altStatusMenuPanelLayout);
        altStatusMenuPanelLayout.setHorizontalGroup(
            altStatusMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(altStatusMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altStatusMenuPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(bttnConfirmarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(370, 370, 370)
                    .addComponent(bttnVoltarProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        altStatusMenuPanelLayout.setVerticalGroup(
            altStatusMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
            .addGroup(altStatusMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altStatusMenuPanelLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(altStatusMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bttnConfirmarAlt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnVoltarProjetos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        projetosAdminMenuPanel.add(altStatusMenuPanel, "altStatusMenuPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projetosAdminMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosAdminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosAdminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projetosAdminMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAltStatusProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAltStatusProjetoActionPerformed
        
        int rowIndex = tabelaProjetosAdmin.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Projeto da tabela para alterar o Status.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            CardLayout content = (CardLayout) (projetosAdminContentPanel.getLayout());
            content.show(projetosAdminContentPanel, "altStatusProjeto");
        
            CardLayout menu = (CardLayout) (projetosAdminMenuPanel.getLayout());
            menu.show(projetosAdminMenuPanel, "altStatusMenuPanel");

            int idProjeto = (int) tabelaProjetosAdmin.getModel().getValueAt(rowIndex, 0);
        
            Projeto proj;
            projController = new ProjetoController();
            proj = projController.getProjetoPorId(idProjeto);

            tituloTextField.setText(proj.getTitulo());
            areaTextField.setText(proj.getArea());
            profOrientadorTextField.setText(proj.getOrientador());
            alunoLiderTextField.setText(proj.getLider());
        }
        
    }//GEN-LAST:event_bttnAltStatusProjetoActionPerformed

    private void bttnVoltarProjetosAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarProjetosAdminActionPerformed
        dispose();
        new HomeAdministrador().setVisible(true);
    }//GEN-LAST:event_bttnVoltarProjetosAdminActionPerformed

    private void bttnVoltarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarProjetosActionPerformed
        CardLayout content = (CardLayout) (projetosAdminContentPanel.getLayout());
        content.show(projetosAdminContentPanel, "projetosAdminIndex");
        
        CardLayout menu = (CardLayout) (projetosAdminMenuPanel.getLayout());
        menu.show(projetosAdminMenuPanel, "indexMenuPanel");
    }//GEN-LAST:event_bttnVoltarProjetosActionPerformed

    private void bttnConfirmarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmarAltActionPerformed
        
        String message = "";
        String emailLider = alunoLiderTextField.getText();
        String novoStatus = (String) statusComboBox.getSelectedItem();
            
        String temp = "Deseja mesmo alterar o Status do Projeto para:\n";
        temp += "\n\t\t" + novoStatus;

        int escolha = JOptionPane.showConfirmDialog(null, temp, "Confirmar alteração de Status?", JOptionPane.OK_CANCEL_OPTION, 0, null);
            
        if (escolha == JOptionPane.OK_OPTION) {

            projController = new ProjetoController();
            message = projController.alterarStatusProjeto(emailLider, novoStatus);

            JOptionPane.showMessageDialog(null, message);

            // volta e atualiza a tabela
            CardLayout content = (CardLayout) (projetosAdminContentPanel.getLayout());
            content.show(projetosAdminContentPanel, "projetosAdminIndex");
        
            CardLayout menu = (CardLayout) (projetosAdminMenuPanel.getLayout());
            menu.show(projetosAdminMenuPanel, "indexMenuPanel");
            
            tabelaProjetosAdmin = projController.updateTable(tabelaProjetosAdmin, "Aprovado");
            tabelaProjetosAdmin.removeColumn(tabelaProjetosAdmin.getColumnModel().getColumn(0));
        }
        
    }//GEN-LAST:event_bttnConfirmarAltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmAcompanharProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmAcompanharProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmAcompanharProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmAcompanharProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmAcompanharProjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel altStatusMenuPanel;
    private javax.swing.JPanel altStatusProjeto;
    private javax.swing.JTextField alunoLiderTextField;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JButton bttnAltStatusProjeto;
    private javax.swing.JButton bttnConfirmarAlt;
    private javax.swing.JButton bttnVoltarProjetos;
    private javax.swing.JButton bttnVoltarProjetosAdmin;
    private javax.swing.JPanel indexMenuPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField profOrientadorTextField;
    private javax.swing.JPanel projetosAdminContentPanel;
    private javax.swing.JPanel projetosAdminIndex;
    private javax.swing.JPanel projetosAdminMenuPanel;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JTable tabelaProjetosAdmin;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables
}
