/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.ProfessorController;
import Model.Tabelas.Professor;
import java.awt.CardLayout;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 17409
 */
public class AdmManterProfessorView extends javax.swing.JFrame {
    
    ProfessorController profController;

    /**
     * Creates new form AlunoView
     */
    public AdmManterProfessorView() {
        initComponents();

        // ligacao com o Controller
        profController = new ProfessorController();
        tabelaProfessores = profController.updateTable(tabelaProfessores);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        professorContentPanel = new javax.swing.JPanel();
        professorIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProfessores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        professorAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        professorName = new javax.swing.JTextField();
        professorEmail = new javax.swing.JTextField();
        professorPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        professorDepartment = new javax.swing.JTextField();
        professorMainDisc = new javax.swing.JTextField();
        bttnConfirmAddProfessor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        professorEdit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        profNomeEdit = new javax.swing.JTextField();
        profEmailEdit = new javax.swing.JTextField();
        profSenhaEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        profDepartEdit = new javax.swing.JTextField();
        profDiscEdit = new javax.swing.JTextField();
        bttnConfirmEditProfessor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        profStatusEdit = new javax.swing.JComboBox();
        professorMenuPanel = new javax.swing.JPanel();
        bttnAddProfessor = new javax.swing.JButton();
        bttnEditProfessor = new javax.swing.JButton();
        bttnDeleteProfessor = new javax.swing.JButton();
        bttnVoltarProfessores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        professorContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        professorContentPanel.setLayout(new java.awt.CardLayout());

        tabelaProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Status", "Departamento", "Disciplina Principal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProfessores);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Professores");

        javax.swing.GroupLayout professorIndexLayout = new javax.swing.GroupLayout(professorIndex);
        professorIndex.setLayout(professorIndexLayout);
        professorIndexLayout.setHorizontalGroup(
            professorIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorIndexLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
        );
        professorIndexLayout.setVerticalGroup(
            professorIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        professorContentPanel.add(professorIndex, "professorIndex");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Adicionar novo Professor");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Departamento:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Disciplina Principal:");

        bttnConfirmAddProfessor.setText("Adicionar");
        bttnConfirmAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmAddProfessorActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Todos os campos são obrigatórios");

        javax.swing.GroupLayout professorAddLayout = new javax.swing.GroupLayout(professorAdd);
        professorAdd.setLayout(professorAddLayout);
        professorAddLayout.setHorizontalGroup(
            professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(159, 159, 159))
            .addGroup(professorAddLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorAddLayout.createSequentialGroup()
                        .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(professorAddLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(professorMainDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorAddLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(professorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorAddLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(professorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorAddLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(professorDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnConfirmAddProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(professorAddLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professorName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addContainerGap())
        );
        professorAddLayout.setVerticalGroup(
            professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(professorName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(professorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(professorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(professorAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(professorMainDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConfirmAddProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        professorContentPanel.add(professorAdd, "professorAdd");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Editar dados do Professor");

        profEmailEdit.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Senha:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Departamento:");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Disciplina Principal:");

        bttnConfirmEditProfessor.setText("Confirmar");
        bttnConfirmEditProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmEditProfessorActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Status:");

        profStatusEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout professorEditLayout = new javax.swing.GroupLayout(professorEdit);
        professorEdit.setLayout(professorEditLayout);
        professorEditLayout.setHorizontalGroup(
            professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(159, 159, 159))
            .addGroup(professorEditLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorEditLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profDiscEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(bttnConfirmEditProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorEditLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profDepartEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorEditLayout.createSequentialGroup()
                        .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(professorEditLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorEditLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorEditLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        professorEditLayout.setVerticalGroup(
            professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(profStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(profEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(profSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profDepartEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(professorEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(profDiscEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConfirmEditProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        professorContentPanel.add(professorEdit, "professorEdit");

        professorMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnAddProfessor.setText("Novo Professor");
        bttnAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddProfessorActionPerformed(evt);
            }
        });

        bttnEditProfessor.setText("Editar Selecionado");
        bttnEditProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditProfessorActionPerformed(evt);
            }
        });

        bttnDeleteProfessor.setText("Excluir Selecionado");
        bttnDeleteProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteProfessorActionPerformed(evt);
            }
        });

        bttnVoltarProfessores.setText("Voltar");
        bttnVoltarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarProfessoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout professorMenuPanelLayout = new javax.swing.GroupLayout(professorMenuPanel);
        professorMenuPanel.setLayout(professorMenuPanelLayout);
        professorMenuPanelLayout.setHorizontalGroup(
            professorMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnAddProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnEditProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnDeleteProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnVoltarProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        professorMenuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bttnAddProfessor, bttnDeleteProfessor, bttnEditProfessor});

        professorMenuPanelLayout.setVerticalGroup(
            professorMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(professorMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAddProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnEditProfessor)
                    .addComponent(bttnDeleteProfessor)
                    .addComponent(bttnVoltarProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        professorMenuPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bttnAddProfessor, bttnDeleteProfessor, bttnEditProfessor});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(professorContentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professorMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professorContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddProfessorActionPerformed
        CardLayout content = (CardLayout) (professorContentPanel.getLayout());
        content.show(professorContentPanel, "professorAdd");
    }//GEN-LAST:event_bttnAddProfessorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout content = (CardLayout) (professorContentPanel.getLayout());
        content.show(professorContentPanel, "professorIndex");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttnConfirmAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmAddProfessorActionPerformed
        
        boolean check = false;
        
        profController = new ProfessorController();
        check = profController.addProfessor(professorName.getText(), professorEmail.getText(), professorPassword.getText(),
                professorDepartment.getText(), professorMainDisc.getText());

        if (check) {
            JOptionPane.showMessageDialog(null, "Professor adicionado com sucesso!");
            
            CardLayout content = (CardLayout) (professorContentPanel.getLayout());
            content.show(professorContentPanel, "professorIndex");
        
            // atualizar tabela
            profController = new ProfessorController();
            tabelaProfessores = profController.updateTable(tabelaProfessores);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível completar a ação. Verifique se todos "
                    + "os campos estão preenchidos (obrigatório).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnConfirmAddProfessorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout content = (CardLayout) (professorContentPanel.getLayout());
        content.show(professorContentPanel, "professorIndex");
        
        // atualizar tabela
        profController = new ProfessorController();
        tabelaProfessores = profController.updateTable(tabelaProfessores);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bttnEditProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditProfessorActionPerformed

        int rowIndex = tabelaProfessores.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Professor da tabela para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
        
            CardLayout content = (CardLayout) (professorContentPanel.getLayout());
            content.show(professorContentPanel, "professorEdit");
            
            String emailProfSelecionado = (String) tabelaProfessores.getModel().getValueAt(rowIndex, 1);
            Professor p;
            profController = new ProfessorController();
            
            p = profController.getProfessorByEmail(emailProfSelecionado);
            
            profNomeEdit.setText(p.getNome());
            profEmailEdit.setText(p.getEmail());
            profSenhaEdit.setText(p.getSenha());
            profStatusEdit.setSelectedItem(p.getStatus());
            profDepartEdit.setText(p.getDepartamento());
            profDiscEdit.setText(p.getDisciplinaPrincipal());
        }

    }//GEN-LAST:event_bttnEditProfessorActionPerformed

    private void bttnConfirmEditProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmEditProfessorActionPerformed
        
        boolean check = false;
        
        profController = new ProfessorController();
        check = profController.updateProfessor(profNomeEdit.getText(), profEmailEdit.getText(), profSenhaEdit.getText(), 
                profDepartEdit.getText(), profDiscEdit.getText(), (String) profStatusEdit.getSelectedItem());
        
        if (check) {
            JOptionPane.showMessageDialog(null, "Professor editado com sucesso!");
            
            CardLayout content = (CardLayout) (professorContentPanel.getLayout());
            content.show(professorContentPanel, "professorIndex");
            
            // atualizar tabela
            profController = new ProfessorController();
            tabelaProfessores = profController.updateTable(tabelaProfessores);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível completar a ação. Erro ao editar Professor.");
        }
        
    }//GEN-LAST:event_bttnConfirmEditProfessorActionPerformed

    private void bttnDeleteProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteProfessorActionPerformed
        CardLayout content = (CardLayout) (professorContentPanel.getLayout());
        content.show(professorContentPanel, "professorDelete");
        
        int rowIndex = tabelaProfessores.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Professor da tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            
            String message = "";
            String emailProfSelec = (String) tabelaProfessores.getModel().getValueAt(rowIndex, 1);
            String nomeProfSelec = (String) tabelaProfessores.getModel().getValueAt(rowIndex, 0);
            String departamentoProfSelec = (String) tabelaProfessores.getModel().getValueAt(rowIndex, 3);
            String discPrincipalProfSelec = (String) tabelaProfessores.getModel().getValueAt(rowIndex, 4);
            
            String temp = "Deseja excluir o seguinte Professor:\n";
            temp += "\n\t\tNome: " + nomeProfSelec;
            temp += "\n\t\tEmail: " + emailProfSelec;
            temp += "\n\t\tDepartamento: " + departamentoProfSelec;
            temp += "\n\t\tDisciplina principal: " + discPrincipalProfSelec;
            temp += "\n\nA exclusão do Professor o tornará 'Inativo', incapacitando-o de orientar de projetos";

            int escolha = JOptionPane.showConfirmDialog(null, temp, "Confirmar exclusão?", JOptionPane.OK_CANCEL_OPTION, 0, null);
            
            if (escolha == JOptionPane.OK_OPTION) {
            
                profController = new ProfessorController();
                message = profController.delProfessor(emailProfSelec);
            
                JOptionPane.showMessageDialog(null, message);
                
                // atualizar tabela
                profController = new ProfessorController();
                tabelaProfessores = profController.updateTable(tabelaProfessores);
            }
        }
    }//GEN-LAST:event_bttnDeleteProfessorActionPerformed

    private void bttnVoltarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarProfessoresActionPerformed
        dispose();
        new HomeAdministrador().setVisible(true);
    }//GEN-LAST:event_bttnVoltarProfessoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmManterProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmManterProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmManterProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmManterProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmManterProfessorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAddProfessor;
    private javax.swing.JButton bttnConfirmAddProfessor;
    private javax.swing.JButton bttnConfirmEditProfessor;
    private javax.swing.JButton bttnDeleteProfessor;
    private javax.swing.JButton bttnEditProfessor;
    private javax.swing.JButton bttnVoltarProfessores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField profDepartEdit;
    private javax.swing.JTextField profDiscEdit;
    private javax.swing.JTextField profEmailEdit;
    private javax.swing.JTextField profNomeEdit;
    private javax.swing.JTextField profSenhaEdit;
    private javax.swing.JComboBox profStatusEdit;
    private javax.swing.JPanel professorAdd;
    private javax.swing.JPanel professorContentPanel;
    private javax.swing.JTextField professorDepartment;
    private javax.swing.JPanel professorEdit;
    private javax.swing.JTextField professorEmail;
    private javax.swing.JPanel professorIndex;
    private javax.swing.JTextField professorMainDisc;
    private javax.swing.JPanel professorMenuPanel;
    private javax.swing.JTextField professorName;
    private javax.swing.JTextField professorPassword;
    private javax.swing.JTable tabelaProfessores;
    // End of variables declaration//GEN-END:variables
}
