
package View;

import Controller.AdministradorController;
import Model.Administrador;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

public class AdmnistradorView extends javax.swing.JFrame {

    AdministradorController admController;
    
    public AdmnistradorView() {
        initComponents();
        
        admController = new AdministradorController();
        tabelaAdministradores = admController.updateTable(tabelaAdministradores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admContentPanel = new javax.swing.JPanel();
        admIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAdministradores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        admAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        admName = new javax.swing.JTextField();
        admEmail = new javax.swing.JTextField();
        admPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bttnConfirmAddAdm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        admEdit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        admNomeEdit = new javax.swing.JTextField();
        admEmailEdit = new javax.swing.JTextField();
        admSenhaEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bttnConfirmEditAdm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        admStatusEdit = new javax.swing.JComboBox();
        admMenuPanel = new javax.swing.JPanel();
        bttnAddAdm = new javax.swing.JButton();
        bttnEditAdm = new javax.swing.JButton();
        bttnDeleteAdm = new javax.swing.JButton();
        bttnVoltarAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        admContentPanel.setLayout(new java.awt.CardLayout());

        tabelaAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAdministradores);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Administradores");

        org.jdesktop.layout.GroupLayout admIndexLayout = new org.jdesktop.layout.GroupLayout(admIndex);
        admIndex.setLayout(admIndexLayout);
        admIndexLayout.setHorizontalGroup(
            admIndexLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admIndexLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admIndexLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .add(178, 178, 178))
        );
        admIndexLayout.setVerticalGroup(
            admIndexLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admIndexLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        admContentPanel.add(admIndex, "admIndex");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Adicionar novo Administrador");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");

        bttnConfirmAddAdm.setText("Adicionar");
        bttnConfirmAddAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmAddAdmActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Todos os campos são obrigatórios");

        org.jdesktop.layout.GroupLayout admAddLayout = new org.jdesktop.layout.GroupLayout(admAdd);
        admAdd.setLayout(admAddLayout);
        admAddLayout.setHorizontalGroup(
            admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admAddLayout.createSequentialGroup()
                .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(admAddLayout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(admPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(admAddLayout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(admEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(admAddLayout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(admName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(bttnConfirmAddAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(143, 143, 143))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                        .add(jLabel15)
                        .addContainerGap())))
        );
        admAddLayout.setVerticalGroup(
            admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admAddLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(admAddLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel15)
                        .add(137, 137, 137)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(admAddLayout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(admName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .add(18, 18, 18)
                        .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(admEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(admAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(admPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(bttnConfirmAddAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(15, 15, 15))
        );

        admContentPanel.add(admAdd, "admAdd");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Editar dados do Administrador");

        admEmailEdit.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Senha:");

        bttnConfirmEditAdm.setText("Confirmar");
        bttnConfirmEditAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmEditAdmActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Status:");

        admStatusEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        org.jdesktop.layout.GroupLayout admEditLayout = new org.jdesktop.layout.GroupLayout(admEdit);
        admEdit.setLayout(admEditLayout);
        admEditLayout.setHorizontalGroup(
            admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admEditLayout.createSequentialGroup()
                .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(admEditLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(bttnConfirmEditAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(admEditLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(admEditLayout.createSequentialGroup()
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(admEmailEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(admEditLayout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(admNomeEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(admEditLayout.createSequentialGroup()
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(admStatusEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(admEditLayout.createSequentialGroup()
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(admSenhaEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admEditLayout.createSequentialGroup()
                .add(0, 172, Short.MAX_VALUE)
                .add(jLabel8)
                .add(128, 128, 128))
        );
        admEditLayout.setVerticalGroup(
            admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, admEditLayout.createSequentialGroup()
                .add(206, 206, 206)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(bttnConfirmEditAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12))
            .add(admEditLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .add(29, 29, 29)
                .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(admNomeEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .add(18, 18, 18)
                .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(admEmailEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(admSenhaEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(admEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(admStatusEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admContentPanel.add(admEdit, "admEdit");

        admMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnAddAdm.setText("Novo Adm");
        bttnAddAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddAdmActionPerformed(evt);
            }
        });

        bttnEditAdm.setText("Editar Selecionado");
        bttnEditAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditAdmActionPerformed(evt);
            }
        });

        bttnDeleteAdm.setText("Excluir Selecionado");
        bttnDeleteAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteAdmActionPerformed(evt);
            }
        });

        bttnVoltarAdm.setText("Voltar");
        bttnVoltarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarAdmActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout admMenuPanelLayout = new org.jdesktop.layout.GroupLayout(admMenuPanel);
        admMenuPanel.setLayout(admMenuPanelLayout);
        admMenuPanelLayout.setHorizontalGroup(
            admMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(bttnAddAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(bttnEditAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(bttnDeleteAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(bttnVoltarAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admMenuPanelLayout.linkSize(new java.awt.Component[] {bttnAddAdm, bttnDeleteAdm, bttnEditAdm}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        admMenuPanelLayout.setVerticalGroup(
            admMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(admMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(admMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bttnAddAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bttnEditAdm)
                    .add(bttnDeleteAdm)
                    .add(bttnVoltarAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        admMenuPanelLayout.linkSize(new java.awt.Component[] {bttnAddAdm, bttnDeleteAdm, bttnEditAdm}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admContentPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, admMenuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(admContentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(admMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConfirmAddAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmAddAdmActionPerformed

        boolean check = false;

        admController = new AdministradorController();
        check = admController.addAdministrador(admName.getText(), admEmail.getText(), admPassword.getText());

        if (check) {
            JOptionPane.showMessageDialog(null, "Administrador adicionado com sucesso!");

            CardLayout content = (CardLayout) (admContentPanel.getLayout());
            content.show(admContentPanel, "admIndex");

            // atualizar tabela
            admController = new AdministradorController();
            tabelaAdministradores = admController.updateTable(tabelaAdministradores);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível completar a ação. Verifique se todos "
                + "os campos estão preenchidos (obrigatório).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnConfirmAddAdmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout content = (CardLayout) (admContentPanel.getLayout());
        content.show(admContentPanel, "admIndex");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttnConfirmEditAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmEditAdmActionPerformed

        boolean check = false;

        admController = new AdministradorController();
        check = admController.updateAdministrador(admNomeEdit.getText(), admEmailEdit.getText(), admSenhaEdit.getText(),
                 (String) admStatusEdit.getSelectedItem());

        if (check) {
            JOptionPane.showMessageDialog(null, "Administrador editado com sucesso!");

            CardLayout content = (CardLayout) (admContentPanel.getLayout());
            content.show(admContentPanel, "admIndex");

            // atualizar tabela
            admController = new AdministradorController();
            tabelaAdministradores = admController.updateTable(tabelaAdministradores);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível completar a ação. Erro ao editar Administrador.");
        }

    }//GEN-LAST:event_bttnConfirmEditAdmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout content = (CardLayout) (admContentPanel.getLayout());
        content.show(admContentPanel, "admIndex");

        // atualizar tabela
        admController = new AdministradorController();
        tabelaAdministradores = admController.updateTable(tabelaAdministradores);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bttnAddAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddAdmActionPerformed
        CardLayout content = (CardLayout) (admContentPanel.getLayout());
        content.show(admContentPanel, "admAdd");
    }//GEN-LAST:event_bttnAddAdmActionPerformed

    private void bttnEditAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditAdmActionPerformed

        int rowIndex = tabelaAdministradores.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Administrador da tabela para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {

            CardLayout content = (CardLayout) (admContentPanel.getLayout());
            content.show(admContentPanel, "admEdit");

            String emailAdmSelecionado = (String) tabelaAdministradores.getModel().getValueAt(rowIndex, 1);
            Administrador adm;
            admController = new AdministradorController();

            adm = admController.getAdmByEmail(emailAdmSelecionado);

            admNomeEdit.setText(adm.getNome());
            admEmailEdit.setText(adm.getEmail());
            admSenhaEdit.setText(adm.getSenha());
            admStatusEdit.setSelectedItem(adm.getStatus());
        }
    }//GEN-LAST:event_bttnEditAdmActionPerformed

    private void bttnDeleteAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteAdmActionPerformed
        CardLayout content = (CardLayout) (admContentPanel.getLayout());
        content.show(admContentPanel, "admDelete");

        int rowIndex = tabelaAdministradores.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Administrador da tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {

            String message = "";
            String emailAdmSelec = (String) tabelaAdministradores.getModel().getValueAt(rowIndex, 1);
            String nomeAdmSelec = (String) tabelaAdministradores.getModel().getValueAt(rowIndex, 0);
            
            String temp = "Deseja excluir o seguinte Administrador:\n";
            temp += "\n\t\tNome: " + nomeAdmSelec;
            temp += "\n\t\tEmail: " + emailAdmSelec;
            temp += "\n\nA exclusão do Administrador o tornará 'Inativo'";

            int escolha = JOptionPane.showConfirmDialog(null, temp, "Confirmar exclusão?", JOptionPane.OK_CANCEL_OPTION, 0, null);
            
            if (escolha == JOptionPane.OK_OPTION) {

                admController = new AdministradorController();
                message = admController.delAdministrador(emailAdmSelec);

                JOptionPane.showMessageDialog(null, message);

                // atualizar tabela
                admController = new AdministradorController();
                tabelaAdministradores = admController.updateTable(tabelaAdministradores);
            }
        }
    }//GEN-LAST:event_bttnDeleteAdmActionPerformed

    private void bttnVoltarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarAdmActionPerformed
        dispose();
        new Index().setVisible(true);
    }//GEN-LAST:event_bttnVoltarAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmnistradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmnistradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmnistradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmnistradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmnistradorView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admAdd;
    private javax.swing.JPanel admContentPanel;
    private javax.swing.JPanel admEdit;
    private javax.swing.JTextField admEmail;
    private javax.swing.JTextField admEmailEdit;
    private javax.swing.JPanel admIndex;
    private javax.swing.JPanel admMenuPanel;
    private javax.swing.JTextField admName;
    private javax.swing.JTextField admNomeEdit;
    private javax.swing.JTextField admPassword;
    private javax.swing.JTextField admSenhaEdit;
    private javax.swing.JComboBox admStatusEdit;
    private javax.swing.JButton bttnAddAdm;
    private javax.swing.JButton bttnConfirmAddAdm;
    private javax.swing.JButton bttnConfirmEditAdm;
    private javax.swing.JButton bttnDeleteAdm;
    private javax.swing.JButton bttnEditAdm;
    private javax.swing.JButton bttnVoltarAdm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAdministradores;
    // End of variables declaration//GEN-END:variables
}
