package View;

import Controller.ProjetoController;
import Controller.Sessao;
import Model.Tabelas.Projeto;
import Utils.XMLParser;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AvaProjetosView extends javax.swing.JFrame {

    ProjetoController projController;
    XMLParser xmlParser;
    Projeto proj;
    private ArrayList<String> titulos;
    private ArrayList<String> questoes;
    private ArrayList<String> respostas;

    int idPergunta;
    int idProjeto;
    double nota;
    String emailAvaliador;
    ArrayList<Double> notas;

    /**
     * Creates new form ProjetosAdministrador
     */
    public AvaProjetosView() {

        initComponents();
        emailAvaliador = Sessao.getInstance().getUsuario().getEmail();

        projController = new ProjetoController();
        tabelaProjetosAvaliador = projController.updateTableProjetosAvaliador(tabelaProjetosAvaliador, emailAvaliador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projetosAvaliadorContentPanel = new javax.swing.JPanel();
        projetosAvaliadorIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProjetosAvaliador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addNotaProjetoPanel = new javax.swing.JPanel();
        questionTitlePanel = new javax.swing.JPanel();
        labelTituloProjeto = new javax.swing.JLabel();
        tituloProjeto = new javax.swing.JLabel();
        questionContentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        quadroResposta = new javax.swing.JTextArea();
        labelNota = new javax.swing.JLabel();
        textoExplicativo = new javax.swing.JLabel();
        questaoProjeto = new javax.swing.JLabel();
        textNota = new javax.swing.JTextField();
        perguntasComboBox = new javax.swing.JComboBox();
        labelPerguntaCombo = new javax.swing.JLabel();
        projetosAvaliadorMenuPanel = new javax.swing.JPanel();
        indexProjetosAvaliadorMenu = new javax.swing.JPanel();
        bttnPreencherAvaliacao = new javax.swing.JButton();
        bttnFinalizarAvaliacao = new javax.swing.JButton();
        bttnVoltar = new javax.swing.JButton();
        preencherAvaliacaoMenu = new javax.swing.JPanel();
        bttnVoltar1 = new javax.swing.JButton();
        bttnAtribuirNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projetosAvaliadorContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projetosAvaliadorContentPanel.setLayout(new java.awt.CardLayout());

        tabelaProjetosAvaliador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Título", "Líder", "Orientador", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProjetosAvaliador);
        if (tabelaProjetosAvaliador.getColumnModel().getColumnCount() > 0) {
            tabelaProjetosAvaliador.getColumnModel().getColumn(0).setResizable(false);
            tabelaProjetosAvaliador.getColumnModel().getColumn(1).setResizable(false);
            tabelaProjetosAvaliador.getColumnModel().getColumn(2).setResizable(false);
            tabelaProjetosAvaliador.getColumnModel().getColumn(3).setResizable(false);
            tabelaProjetosAvaliador.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Projetos");

        javax.swing.GroupLayout projetosAvaliadorIndexLayout = new javax.swing.GroupLayout(projetosAvaliadorIndex);
        projetosAvaliadorIndex.setLayout(projetosAvaliadorIndexLayout);
        projetosAvaliadorIndexLayout.setHorizontalGroup(
            projetosAvaliadorIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetosAvaliadorIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(projetosAvaliadorIndexLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projetosAvaliadorIndexLayout.setVerticalGroup(
            projetosAvaliadorIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projetosAvaliadorIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        projetosAvaliadorContentPanel.add(projetosAvaliadorIndex, "avaliadorIndex");

        questionTitlePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloProjeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloProjeto.setText("Titulo do Projeto:");

        tituloProjeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloProjeto.setText(" ");

        javax.swing.GroupLayout questionTitlePanelLayout = new javax.swing.GroupLayout(questionTitlePanel);
        questionTitlePanel.setLayout(questionTitlePanelLayout);
        questionTitlePanelLayout.setHorizontalGroup(
            questionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        questionTitlePanelLayout.setVerticalGroup(
            questionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(questionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloProjeto)
                    .addComponent(tituloProjeto))
                .addContainerGap())
        );

        quadroResposta.setColumns(20);
        quadroResposta.setRows(5);
        quadroResposta.setEnabled(false);
        jScrollPane2.setViewportView(quadroResposta);

        labelNota.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNota.setText("Nota:");

        textoExplicativo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textoExplicativo.setText("Quadro _ - ");

        questaoProjeto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questaoProjeto.setText("Questão.");
        questaoProjeto.setMaximumSize(new java.awt.Dimension(691, 20));

        textNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaActionPerformed(evt);
            }
        });
        textNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNotaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNotaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout questionContentPanelLayout = new javax.swing.GroupLayout(questionContentPanel);
        questionContentPanel.setLayout(questionContentPanelLayout);
        questionContentPanelLayout.setHorizontalGroup(
            questionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(questionContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionContentPanelLayout.createSequentialGroup()
                        .addGroup(questionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoExplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(questionContentPanelLayout.createSequentialGroup()
                        .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        questionContentPanelLayout.setVerticalGroup(
            questionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoExplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(questionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionContentPanelLayout.createSequentialGroup()
                        .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        perguntasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        perguntasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perguntasComboBoxActionPerformed(evt);
            }
        });

        labelPerguntaCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPerguntaCombo.setText("Escolha a pergunta:");

        javax.swing.GroupLayout addNotaProjetoPanelLayout = new javax.swing.GroupLayout(addNotaProjetoPanel);
        addNotaProjetoPanel.setLayout(addNotaProjetoPanelLayout);
        addNotaProjetoPanelLayout.setHorizontalGroup(
            addNotaProjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNotaProjetoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNotaProjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addNotaProjetoPanelLayout.createSequentialGroup()
                        .addComponent(questionTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(labelPerguntaCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(perguntasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        addNotaProjetoPanelLayout.setVerticalGroup(
            addNotaProjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNotaProjetoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNotaProjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addNotaProjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perguntasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPerguntaCombo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        projetosAvaliadorContentPanel.add(addNotaProjetoPanel, "attrNota");

        projetosAvaliadorMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projetosAvaliadorMenuPanel.setLayout(new java.awt.CardLayout());

        bttnPreencherAvaliacao.setText("Preencher Avaliação");
        bttnPreencherAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPreencherAvaliacaoActionPerformed(evt);
            }
        });

        bttnFinalizarAvaliacao.setText("Finalizar Avaliação");
        bttnFinalizarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnFinalizarAvaliacaoActionPerformed(evt);
            }
        });

        bttnVoltar.setText("Voltar");
        bttnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indexProjetosAvaliadorMenuLayout = new javax.swing.GroupLayout(indexProjetosAvaliadorMenu);
        indexProjetosAvaliadorMenu.setLayout(indexProjetosAvaliadorMenuLayout);
        indexProjetosAvaliadorMenuLayout.setHorizontalGroup(
            indexProjetosAvaliadorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexProjetosAvaliadorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnPreencherAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnFinalizarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        indexProjetosAvaliadorMenuLayout.setVerticalGroup(
            indexProjetosAvaliadorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexProjetosAvaliadorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexProjetosAvaliadorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnPreencherAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnFinalizarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        indexProjetosAvaliadorMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bttnFinalizarAvaliacao, bttnPreencherAvaliacao, bttnVoltar});

        projetosAvaliadorMenuPanel.add(indexProjetosAvaliadorMenu, "indexProjetosAvaliadorMenu");

        bttnVoltar1.setText("Voltar");
        bttnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltar1ActionPerformed(evt);
            }
        });

        bttnAtribuirNota.setText("Atribuir Nota");
        bttnAtribuirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtribuirNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout preencherAvaliacaoMenuLayout = new javax.swing.GroupLayout(preencherAvaliacaoMenu);
        preencherAvaliacaoMenu.setLayout(preencherAvaliacaoMenuLayout);
        preencherAvaliacaoMenuLayout.setHorizontalGroup(
            preencherAvaliacaoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preencherAvaliacaoMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnAtribuirNota, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addComponent(bttnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        preencherAvaliacaoMenuLayout.setVerticalGroup(
            preencherAvaliacaoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preencherAvaliacaoMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preencherAvaliacaoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAtribuirNota)
                    .addComponent(bttnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        preencherAvaliacaoMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bttnAtribuirNota, bttnVoltar1});

        projetosAvaliadorMenuPanel.add(preencherAvaliacaoMenu, "preencherAvaliacaoMenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosAvaliadorContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(projetosAvaliadorMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosAvaliadorContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projetosAvaliadorMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnPreencherAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPreencherAvaliacaoActionPerformed

        textoExplicativo.setText("Quadro _ -");
        questaoProjeto.setText("Questão");
        quadroResposta.setText("");
        perguntasComboBox.setSelectedIndex(0);

        notas = new ArrayList<>();

        int rowIndex = tabelaProjetosAvaliador.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Escolha um Projeto da tabela para avaliar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            idProjeto = (int) tabelaProjetosAvaliador.getModel().getValueAt(rowIndex, 0);

            CardLayout content = (CardLayout) (projetosAvaliadorContentPanel.getLayout());
            content.show(projetosAvaliadorContentPanel, "attrNota");
            
            CardLayout menu = (CardLayout) (projetosAvaliadorMenuPanel.getLayout());
            menu.show(projetosAvaliadorMenuPanel, "preencherAvaliacaoMenu");

            projController = new ProjetoController();
            proj = projController.getProjetoPorId(idProjeto);
            notas = projController.getNotasProjetoPorAvaliador(idProjeto, emailAvaliador);

            textNota.setText("");

            titulos = projController.getPerguntas(0);
            questoes = projController.getPerguntas(1);
            respostas = proj.getRespostas();

            tituloProjeto.setText(proj.getTitulo());
            if (perguntasComboBox.getItemCount() <= 1) {
                for (int i = 1; i <= titulos.size(); i++) {
                    perguntasComboBox.addItem("Pergunta " + i);
                }
            }
        }
    }//GEN-LAST:event_bttnPreencherAvaliacaoActionPerformed

    private void bttnFinalizarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnFinalizarAvaliacaoActionPerformed

        int rowIndex = tabelaProjetosAvaliador.getSelectedRow();
        
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Escolha um Projeto da tabela para finalizar avaliação.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
        
            idProjeto = (int) tabelaProjetosAvaliador.getModel().getValueAt(rowIndex, 0);

            if (projController.checkNumeroAvaliadores(idProjeto) >= 3) {
                if (projController.checkFinalizarProjeto(idProjeto)) {
                    if (projController.finalizaProjeto(idProjeto)) {
                        JOptionPane.showMessageDialog(perguntasComboBox, "Projeto finalizado com sucesso.");
                    } else {
                        JOptionPane.showMessageDialog(perguntasComboBox, "Houve um erro ao finalizar o projeto.");
                    }
                } else {
                    JOptionPane.showMessageDialog(perguntasComboBox, "Verifique se todos os avaliadores atribuiram"
                            + " suas notas.");
                }
            } else {
                JOptionPane.showMessageDialog(perguntasComboBox, "O projeto precisa ter no mínimo três avaliadores"
                        + " para ser finalizado.");
            }
        }

    }//GEN-LAST:event_bttnFinalizarAvaliacaoActionPerformed

    private void bttnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarActionPerformed
        dispose();
        new HomeAvaliador().setVisible(true);
    }//GEN-LAST:event_bttnVoltarActionPerformed

    private void perguntasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perguntasComboBoxActionPerformed

        int perguntaId = perguntasComboBox.getSelectedIndex();

        perguntaId--;

        if (perguntaId >= 0) {
            int temp = perguntaId + 1;
            textoExplicativo.setText("Quadro " + temp + " - " + titulos.get(perguntaId));
            questaoProjeto.setText(questoes.get(perguntaId));

            if (respostas.size() > 0 && respostas.get(perguntaId) != null) {
                quadroResposta.setText(respostas.get(perguntaId));
            } else {
                quadroResposta.setText("");
            }

            Double nota = notas.get(perguntaId);
            if (nota != -1) {
                textNota.setText(nota.toString());
            } else {
                textNota.setText("");
            }
        } else {
            textoExplicativo.setText("Quadro _ -");
            questaoProjeto.setText("Questão");
            quadroResposta.setText("");
            textNota.setText("");
        }
        
    }//GEN-LAST:event_perguntasComboBoxActionPerformed

    private void textNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaActionPerformed

    private void textNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNotaKeyTyped

    }//GEN-LAST:event_textNotaKeyTyped

    private void textNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNotaKeyPressed

    }//GEN-LAST:event_textNotaKeyPressed

    private void bttnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltar1ActionPerformed
        CardLayout content = (CardLayout) (projetosAvaliadorContentPanel.getLayout());
        content.show(projetosAvaliadorContentPanel, "avaliadorIndex");
        
        CardLayout menu = (CardLayout) (projetosAvaliadorMenuPanel.getLayout());
        menu.show(projetosAvaliadorMenuPanel, "indexProjetosAvaliadorMenu");
    }//GEN-LAST:event_bttnVoltar1ActionPerformed

    private void bttnAtribuirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtribuirNotaActionPerformed
        
        idPergunta = perguntasComboBox.getSelectedIndex();
        System.out.println("ID PERGUNTA: " + idPergunta);
        
        if (idPergunta == 0) {
            JOptionPane.showMessageDialog(rootPane, "Escolha uma pergunta para atribuir a nota");
        } else {
            if (projController.checkNota(textNota.getText())) {
                String notaText = textNota.getText().replace(",", ".");
                nota = Double.parseDouble(notaText);
                //idPergunta = perguntasComboBox.getSelectedIndex();
                emailAvaliador = Sessao.getInstance().getUsuario().getEmail();
                if (projController.atribuirNotaPergunta(idPergunta, emailAvaliador, idProjeto, nota)) {
                    JOptionPane.showMessageDialog(rootPane, "Nota atribuída com sucesso");
                    notas = projController.getNotasProjetoPorAvaliador(idProjeto, emailAvaliador);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Houve um erro ao atribuir a nota");
                }
            } else {
                JOptionPane.showMessageDialog(perguntasComboBox, "Valor de nota incorrreto."
                    + "\nInsira valores de 0 a 10.");
            }
        }
    }//GEN-LAST:event_bttnAtribuirNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaProjetosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addNotaProjetoPanel;
    private javax.swing.JButton bttnAtribuirNota;
    private javax.swing.JButton bttnFinalizarAvaliacao;
    private javax.swing.JButton bttnPreencherAvaliacao;
    private javax.swing.JButton bttnVoltar;
    private javax.swing.JButton bttnVoltar1;
    private javax.swing.JPanel indexProjetosAvaliadorMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelPerguntaCombo;
    private javax.swing.JLabel labelTituloProjeto;
    private javax.swing.JComboBox perguntasComboBox;
    private javax.swing.JPanel preencherAvaliacaoMenu;
    private javax.swing.JPanel projetosAvaliadorContentPanel;
    private javax.swing.JPanel projetosAvaliadorIndex;
    private javax.swing.JPanel projetosAvaliadorMenuPanel;
    private javax.swing.JTextArea quadroResposta;
    private javax.swing.JLabel questaoProjeto;
    private javax.swing.JPanel questionContentPanel;
    private javax.swing.JPanel questionTitlePanel;
    private javax.swing.JTable tabelaProjetosAvaliador;
    private javax.swing.JTextField textNota;
    private javax.swing.JLabel textoExplicativo;
    private javax.swing.JLabel tituloProjeto;
    // End of variables declaration//GEN-END:variables
}
