
package View;

import Controller.ProfessorController;
import Controller.ProjetoController;
import Model.Tabelas.Professor;
import Model.Tabelas.Projeto;
import Utils.XMLParser;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom2.JDOMException;

public class ProfProjetosView extends javax.swing.JFrame {

    private ProjetoController projController;
    private ProfessorController profController;
    private String userEmail;
    private XMLParser xmlParser;

    /**
     * Creates new form ProjetosAdministrador
     */
    public ProfProjetosView(String loggedUserEmail) {
        initComponents();
        
        userEmail = loggedUserEmail;
        
        projController = new ProjetoController();
        profController = new ProfessorController();

        // precisou buscar o nome do professor
        Professor prof;
        prof = profController.getProfessorByEmail(userEmail);

        // a busca dos projetos que um prof. orienta eh pelo nome, nao email
        tabelaProjetosProf = projController.updateTableProjetosOrientador(tabelaProjetosProf, prof.getNome());
        
        //System.out.println("Id: " + tabelaProjetosAdmin.getModel().getValueAt(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projetosProfContentPanel = new javax.swing.JPanel();
        projetosProfIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProjetosProf = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addComentProjeto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTituloProjeto = new javax.swing.JLabel();
        tituloProjeto = new javax.swing.JLabel();
        textoExplicativo = new javax.swing.JLabel();
        questaoProjeto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        quadroResposta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        quadroComentarioProf = new javax.swing.JTextArea();
        labelComentProf = new javax.swing.JLabel();
        projetosProfMenuPanel = new javax.swing.JPanel();
        bttnAddComentarios = new javax.swing.JButton();
        bttnVisualizarRespostas = new javax.swing.JButton();
        bttnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projetosProfContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projetosProfContentPanel.setLayout(new java.awt.CardLayout());

        tabelaProjetosProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Título", "Líder", "Orientador", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProjetosProf);
        if (tabelaProjetosProf.getColumnModel().getColumnCount() > 0) {
            tabelaProjetosProf.getColumnModel().getColumn(0).setResizable(false);
            tabelaProjetosProf.getColumnModel().getColumn(1).setResizable(false);
            tabelaProjetosProf.getColumnModel().getColumn(2).setResizable(false);
            tabelaProjetosProf.getColumnModel().getColumn(3).setResizable(false);
            tabelaProjetosProf.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Projetos");

        javax.swing.GroupLayout projetosProfIndexLayout = new javax.swing.GroupLayout(projetosProfIndex);
        projetosProfIndex.setLayout(projetosProfIndexLayout);
        projetosProfIndexLayout.setHorizontalGroup(
            projetosProfIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetosProfIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projetosProfIndexLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
        );
        projetosProfIndexLayout.setVerticalGroup(
            projetosProfIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projetosProfIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        projetosProfContentPanel.add(projetosProfIndex, "professorIndex");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloProjeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloProjeto.setText("Titulo do Projeto:");

        tituloProjeto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloProjeto.setText("pegar depois");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloProjeto)
                    .addComponent(tituloProjeto))
                .addContainerGap())
        );

        textoExplicativo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textoExplicativo.setText("ushduasudiasd");

        questaoProjeto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questaoProjeto.setText("asduiahsuidh uiashudi??");

        quadroResposta.setColumns(20);
        quadroResposta.setRows(5);
        jScrollPane2.setViewportView(quadroResposta);

        quadroComentarioProf.setColumns(20);
        quadroComentarioProf.setRows(5);
        jScrollPane3.setViewportView(quadroComentarioProf);

        labelComentProf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelComentProf.setText("Comentário do Professor Orientador");

        javax.swing.GroupLayout addComentProjetoLayout = new javax.swing.GroupLayout(addComentProjeto);
        addComentProjeto.setLayout(addComentProjetoLayout);
        addComentProjetoLayout.setHorizontalGroup(
            addComentProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addComentProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addComentProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(labelComentProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoExplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        addComentProjetoLayout.setVerticalGroup(
            addComentProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addComentProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoExplicativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questaoProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelComentProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        projetosProfContentPanel.add(addComentProjeto, "addComentProjeto");

        projetosProfMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnAddComentarios.setText("Adicionar Comentários");
        bttnAddComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddComentariosActionPerformed(evt);
            }
        });

        bttnVisualizarRespostas.setText("Visualizar Respostas");
        bttnVisualizarRespostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVisualizarRespostasActionPerformed(evt);
            }
        });

        bttnVoltar.setText("Voltar");
        bttnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projetosProfMenuPanelLayout = new javax.swing.GroupLayout(projetosProfMenuPanel);
        projetosProfMenuPanel.setLayout(projetosProfMenuPanelLayout);
        projetosProfMenuPanelLayout.setHorizontalGroup(
            projetosProfMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetosProfMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnAddComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnVisualizarRespostas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        projetosProfMenuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bttnAddComentarios, bttnVisualizarRespostas});

        projetosProfMenuPanelLayout.setVerticalGroup(
            projetosProfMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetosProfMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projetosProfMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bttnAddComentarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projetosProfMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttnVisualizarRespostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        projetosProfMenuPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bttnAddComentarios, bttnVisualizarRespostas, bttnVoltar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projetosProfMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosProfContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetosProfContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projetosProfMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAddComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddComentariosActionPerformed
        
        int rowIndex = tabelaProjetosProf.getSelectedRow();

        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null,"Escolha um Projeto da tabela para adicionar comentários.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            CardLayout content = (CardLayout) (projetosProfContentPanel.getLayout());
            content.show(projetosProfContentPanel, "addComentProjeto");

            xmlParser = new XMLParser();
            ArrayList<String> titulos = new ArrayList<>();
            ArrayList<String> questoes = new ArrayList<>();

            int idProjeto = (int) tabelaProjetosProf.getModel().getValueAt(rowIndex, 0);
        
            Projeto proj;
            projController = new ProjetoController();
            proj = projController.getProjetoPorId(idProjeto);

            // PASSAR ISSO PRO CONTROLLER
            
            // ta certo isso aqui???
            try {
                try {
                    titulos = xmlParser.getTitulos();
                    questoes = xmlParser.getQuestoes();
                } catch (IOException ex) {
                    Logger.getLogger(ProfProjetosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (JDOMException ex) {
                Logger.getLogger(ProfProjetosView.class.getName()).log(Level.SEVERE, null, ex);
            }


            textoExplicativo.setText("Quadro 1 - " + titulos.get(0));
            questaoProjeto.setText(questoes.get(0));
            quadroResposta.setText(proj.getRespostas().get(0));
        }

    }//GEN-LAST:event_bttnAddComentariosActionPerformed

    private void bttnVisualizarRespostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVisualizarRespostasActionPerformed

//        int rowIndex = tabelaProjetosAdmin.getSelectedRow();
//
//        if (rowIndex == -1) {
//            JOptionPane.showMessageDialog(null,"Escolha um Professor da tabela para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
//        } else {
//
//            CardLayout content = (CardLayout) (projetosAdminContentPanel.getLayout());
//            content.show(projetosAdminContentPanel, "professorEdit");
//
//            String emailProfSelecionado = (String) tabelaProjetosAdmin.getModel().getValueAt(rowIndex, 1);
//            Professor p;
//            profController = new ProfessorController();
//
//            p = profController.getProfessorByEmail(emailProfSelecionado);
//
//            profNomeEdit.setText(p.getNome());
//            profEmailEdit.setText(p.getEmail());
//            profSenhaEdit.setText(p.getSenha());
//            profStatusEdit.setSelectedItem(p.getStatus());
//            profDepartEdit.setText(p.getDepartamento());
//            profDiscEdit.setText(p.getDisciplinaPrincipal());
        //}
    }//GEN-LAST:event_bttnVisualizarRespostasActionPerformed

    private void bttnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarActionPerformed
        dispose();
        new HomeProfessor(userEmail).setVisible(true);
    }//GEN-LAST:event_bttnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfProjetosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProfProjetosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addComentProjeto;
    private javax.swing.JButton bttnAddComentarios;
    private javax.swing.JButton bttnVisualizarRespostas;
    private javax.swing.JButton bttnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelComentProf;
    private javax.swing.JLabel labelTituloProjeto;
    private javax.swing.JPanel projetosProfContentPanel;
    private javax.swing.JPanel projetosProfIndex;
    private javax.swing.JPanel projetosProfMenuPanel;
    private javax.swing.JTextArea quadroComentarioProf;
    private javax.swing.JTextArea quadroResposta;
    private javax.swing.JLabel questaoProjeto;
    private javax.swing.JTable tabelaProjetosProf;
    private javax.swing.JLabel textoExplicativo;
    private javax.swing.JLabel tituloProjeto;
    // End of variables declaration//GEN-END:variables
}
